Add an inbox getAll endpoint.
digitalbazaar/bedrock-ldn-receiver pull request #2
Opened 2017-02-16 22:18 UTC by mattcollier

Dependent PR: https://github.com/digitalbazaar/bedrock-ldn-inbox/pull/2

See note on that PR wrt possible DOS style attack.

2017-02-21 23:41 UTC, dlongley requested changes

2017-02-21 23:41 UTC, dlongley commented on lib/index.js
> +        brLdnInbox.inboxes.getAll(identity, query, fields, options, callback);
This should not return records directly but rather just inboxes.

2017-02-21 23:41 UTC, dlongley commented on lib/index.js
> +  // get inbox info, including list of messages
Is this comment right? Are lists of messages returned? If so, is that what we want? I would think not.

2017-02-22 15:53 UTC, mattcollier commented
@dlongley ready for another pass.

2017-02-22 17:16 UTC, dlongley commented on lib/index.js
> +          query.owner = database.hash(identity.id);
Do we actually want this as the default? I think there should be no default.

2017-02-22 17:30 UTC, mattcollier commented on lib/index.js
> +          query.owner = database.hash(identity.id);
removed.

2017-02-22 17:31 UTC, mattcollier commented
@dlongley ready for another pass.

2017-02-22 17:42 UTC, dlongley approved these changes

2017-02-22 17:48 UTC, merged